---
- name: Set domain to {{ domain }}
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "^#Domains="
    line: "Domains={{ domain }}"
  notify: "Restart systemd-resolved"
  tags: domain

