---
- name: Set hostname
  hostname:
    name: "grafana.{{domain}}"

- name: Install grafana key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Install grafana repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Install packages
  apt:
    name:
      - grafana
    state: present
    update_cache: true
    cache_valid_time: 3000

- name: Start up Grafana service
  systemd_service:
    name: grafana-server
    state: started
    enabled: true
    daemon-reload: true

- name: Copy prometheus datasource file to provisioning
  copy:
    src: prometheus.yaml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yaml
    owner: grafana
    group: grafana
  notify: Restart Grafana

