---
- name: Set hostname
  hostname:
    name: "prometheus.{{domain}}"

- name: Install packages
  apt:
    name:
      - prometheus
    state: present
    update_cache: true
    cache_valid_time: 3000

- name: Update Prometheus Config
  blockinfile:
    dest: /etc/prometheus/prometheus.yml
    insertafter:
    block: "{{ lookup('template', 'prometheus.yml.j2') }}"
  notify:
    - Restart Rrometheus
